package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// GeneratedDocument represents a document generated from a template for a specific case
type GeneratedDocument struct {
	ID        string         `gorm:"type:uuid;primarykey" json:"id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`

	// Firm relationship (multi-tenant scoping)
	FirmID string `gorm:"type:uuid;not null;index" json:"firm_id"`
	Firm   Firm   `gorm:"foreignKey:FirmID" json:"firm,omitempty"`

	// Template relationship (source template)
	TemplateID      string           `gorm:"type:uuid;not null;index" json:"template_id"`
	Template        DocumentTemplate `gorm:"foreignKey:TemplateID" json:"template,omitempty"`
	TemplateVersion int              `gorm:"not null" json:"template_version"` // Snapshot of template version at generation time

	// Case relationship
	CaseID string `gorm:"type:uuid;not null;index" json:"case_id"`
	Case   Case   `gorm:"foreignKey:CaseID" json:"case,omitempty"`

	// Document details
	Name         string `gorm:"not null" json:"name"`
	FinalContent string `gorm:"type:text;not null" json:"-"` // Rendered HTML snapshot (not exposed in JSON)

	// File storage
	FileName string `gorm:"not null" json:"file_name"`
	FilePath string `gorm:"not null" json:"-"` // Not exposed in JSON for security
	FileSize int64  `gorm:"not null" json:"file_size"`

	// Generated by
	GeneratedByID string `gorm:"type:uuid;not null" json:"generated_by_id"`
	GeneratedBy   User   `gorm:"foreignKey:GeneratedByID" json:"generated_by,omitempty"`

	// Link to archived CaseDocument (optional, created when auto-archiving)
	CaseDocumentID *string       `gorm:"type:uuid" json:"case_document_id,omitempty"`
	CaseDocument   *CaseDocument `gorm:"foreignKey:CaseDocumentID" json:"case_document,omitempty"`
}

// BeforeCreate hook to generate UUID
func (g *GeneratedDocument) BeforeCreate(tx *gorm.DB) error {
	if g.ID == "" {
		g.ID = uuid.New().String()
	}
	return nil
}

// TableName specifies the table name for GeneratedDocument model
func (GeneratedDocument) TableName() string {
	return "generated_documents"
}

// GetDownloadURL returns a safe download URL for this generated document
func (g *GeneratedDocument) GetDownloadURL() string {
	return "/api/cases/" + g.CaseID + "/generated/" + g.ID + "/download"
}
